src/FiboBase/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HarmonicPatternBase.Controllers
{
    public class InfoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Patterns()
        {
            return View();
        }

        public IActionResult Reactions()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

src/FiboBase/Controllers/PatternsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HarmonicPatternsBase.Repositories.Abstract;
using HarmonicPatternsBase.Models.PatternViewModels;
using HarmonicPatternsBase.Repositories;

namespace HarmonicPatternsBase.Controllers
{
    public class PatternsController : Controller
    {
        private readonly IHarmonicPatternsRepo _harmonicPatternsRepo;

        public PatternsController(IHarmonicPatternsRepo harmonicPatternsRepo)
        {
            _harmonicPatternsRepo = harmonicPatternsRepo;
        }

        public async Task<IActionResult> Index()
        {
            var model = new PatternsIndexViewModel
            {
                Patterns = await _harmonicPatternsRepo.GetPatternTypesAsync()
            };
            return View(model);
        }

        public async Task<IActionResult> Details(int Id)
        {
            var model = new PatternsDetailsViewModel
            {
                Pattern = await _harmonicPatternsRepo.GetPatternTypeAsync(Id)
            };
            return View(model);
        }
    }
}

src/FiboBase/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HarmonicPatternsBase.Repositories.Abstract;
using HarmonicPatternsBase.Models.StatisticsViewModels;
using HarmonicPatternsBase.Repositories;
using HarmonicPatternsBase.Models.StatisticModels;
using HarmonicPatternsBase.Data;
using HarmonicPatternBase.Repositories.Abstract;

namespace HarmonicPatternsBase.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHarmonicPatternsRepo _harmonicPatternsRepo;
        private readonly IStatisticsRepo _statisticsRepo;
        private readonly IUsersRepo _usersRepo;

        public StatisticsController(
            ApplicationDbContext context,
            IHarmonicPatternsRepo harmonicPatternsRepo,
            IStatisticsRepo statisticsRepo,
            IUsersRepo usersRepo)
        {
            _context = context;
            _harmonicPatternsRepo = harmonicPatternsRepo;
            _statisticsRepo = statisticsRepo;
            _usersRepo = usersRepo;
        }

        public async Task<IActionResult> Index(
            int? intervalId = null,
            int? patternTypeId = null,
            int? instrumentId = null,
            int? patternDirectId = null,
            DateTime? dateSince = null,
            DateTime? dateTo = null,
            DateTime? addDateSince = null,
            DateTime? addDateTo = null,
            string userId = null)
        {
            var statisticsData = await _statisticsRepo.GetHarmonicPatternStatisticisticDataAsync(
                intervalId,
                patternTypeId,
                instrumentId,
                patternDirectId,
                dateSince,
                dateTo,
                addDateSince,
                addDateTo);
            var reactionIds = _statisticsRepo.GetReactionIds();

            var model = new StatisticsIndexViewModel
            {
                DateSince = dateSince,
                DateTo = dateTo,
                AddDateSince = addDateSince,
                AddDateTo = addDateTo,

                Intervals = await _harmonicPatternsRepo.GetIntervalsAsync(),
                PatternTypes = await _harmonicPatternsRepo.GetPatternTypesAsync(),
                PatternDirects = await _harmonicPatternsRepo.GetPatternDirectsAsync(),
                ReactionLevels = await _harmonicPatternsRepo.GetReactionLvlsAsync(),

                SelectedInterval = await _harmonicPatternsRepo.GetIntervalAsync(intervalId),
                SelectedPattern = await _harmonicPatternsRepo.GetPatternTypeAsync(patternTypeId),
                SelectedInstrument = await _harmonicPatternsRepo.GetInstrumentAsync(instrumentId),
                SelectedDirect = await _harmonicPatternsRepo.GetPatternDirectAsync(patternDirectId),

                SelectedPatternId = patternTypeId,
                SelectedIntervalId = intervalId,
                SelectedInstrumentId = instrumentId,
                SelectedDirectId = patternDirectId,
                SelectedUserId = userId,

                Statistics = new HarmonicPatternsStatistic(statisticsData, reactionIds, GetStatisticsMode.Full),
            };

            if (userId != null)
            {
                model.SelectedUser = await _usersRepo.GetUserAsync(userId);
            }
            else
            {
                model.SelectedUser = null;
            }

            model.SetInstruments(await _harmonicPatternsRepo.GetInstrumentsAsync());

            DateTime d = DateTime.Now;

            if (dateSince != null)
            {
                d = (DateTime)dateSince;
                model.DateSinceString = d.Year.ToString() + "-" + d.Month.ToString("00") + "-" + d.Day.ToString("00");
            }

            if (dateTo != null)
            {
                d = (DateTime)dateTo;
                model.DateToString = d.Year.ToString() + "-" + d.Month.ToString("00") + "-" + d.Day.ToString("00");
            }

            if (addDateSince != null)
            {
                d = (DateTime)addDateSince;
                model.AddDateSinceString = d.Year.ToString() + "-" + d.Month.ToString("00") + "-" + d.Day.ToString("00");
            }

            if (addDateTo != null)
            {
                d = (DateTime)addDateTo;
                model.AddDateToString = d.Year.ToString() + "-" + d.Month.ToString("00") + "-" + d.Day.ToString("00");
            }

            return View(model);
        }
    }
}

src/FiboBase/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HarmonicPatternsBase.Models.UserViewModels;
using HarmonicPatternBase.Repositories.Abstract;

namespace HarmonicPatternsBase.Controllers
{
    public class UserController : Controller
    {
        private IUsersRepo _usersRepo;

        public UserController(IUsersRepo usersRepo)
        {
            _usersRepo = usersRepo;
        }

        public async Task<IActionResult> Index(string userId)
        {
            var model = new UserIndexViewModel();

            if(userId != null)
            {
                model.User = await _usersRepo.GetUserAsync(userId);
            }
            else
            {
                model.User = null;
            }

            return View(model);
        }
    }
}

src/FiboBase/Views/Shared/_HarmnonicPatternTile.cshtml
@model HarmonicPatternsBase.Models.HarmonicPattern

@{ 
    string imageContent = "~/images/patterns/uklad1.png";
    string userImageContent = "~/images/DefaultUserPhoto.png";

    var r = new Random();
    var i = r.Next(0, 5);
    if (i == 0)
    {
        imageContent = "~/images/patterns/uklad1.png";
    }
    else if (i == 1)
    {
        imageContent = "~/images/patterns/uklad2.png";
    }
    else if (i == 2)
    {
        imageContent = "~/images/patterns/uklad3.png";
    }
    else if (i == 3)
    {
        imageContent = "~/images/patterns/uklad4.png";
    }
}
<div class="item">

    @if (Model.Image.Length > 5)
    {
        var base64 = Convert.ToBase64String(Model.Image);
        imageContent = String.Format("data:image/gif;base64,{0}", base64);
    }

    <div style="margin-bottom:10px;">
        <a asp-action="Edit" class="btn button-purple">@Model.Instrument.Name</a>
        <a asp-action="Edit" class="btn button-green">@Model.Interval.Name</a>
        <a asp-controller="Patterns" asp-action="Details" asp-route-id="@Model.PatternType.Id" class="btn button-blue">@Model.PatternType.Name</a>
        <a asp-action="Edit" class="btn button-pink">@Model.PatternDirect.Name</a>
    </div>

    <div style="margin-bottom:10px;">
        @if (Model.User == null)
        {
            <img src='~/images/DefaultUserPhoto.png' class="img-circle" style="height:50px; width:50px; display:inline-block;" />
        }
        else
        {
            var base64 = Convert.ToBase64String(Model.User.Avatar);
            userImageContent = String.Format("data:image/gif;base64,{0}", base64);
            <img src='@userImageContent' class="img-circle" style="height:50px; width:50px; display:inline-block;" />
        }

        

        @if (Model.User == null)
        {
            <a asp-action="Index" asp-controller="User" asp-route-userid="@Model.UserId" class="text text-blue" style="margin-left:5px; display:inline-block; font-size:12px;">NIEZNANY UZYTKOWNIK</a>
        }
        else
        {
            <a asp-action="Index" asp-controller="User" asp-route-userid="@Model.UserId" class="text text-blue" style="margin-left:5px; display:inline-block; font-size:12px;">@Model.User.Nick.ToUpper()</a>
        }


    </div>

    <a asp-action="Details" asp-route-id="@Model.Id">
        <div style="text-align:center">
            <img src='@imageContent' class="img-rounded" style="max-width:230px;" asp-append-version="true" />
        </div>
    </a>

    <div class="text row" style="margin-top:10px; font-size:12px;">
        <div class="col-md-5">
            <p>
                NA RYNKU:
            </p>
        </div>
        <div class="col-md-7">
            <p>
                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                @Html.DisplayFor(modelItem => Model.Date)

            </p>
            <p>
                <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                @Model.Date.TimeOfDay
            </p>
        </div>
    </div>
    <div class="text row" style="margin-top:10px; font-size:12px;">
        <div class="col-md-5">
            <p>
                DODANO:
            </p>
        </div>
        <div class="col-md-7">
            <p>
                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                @Html.DisplayFor(modelItem => Model.AddDate)

            </p>
        </div>
    </div>

</div>

src/FiboBase/Views/Shared/_HarmonicPatternTableItem.cshtml
@model HarmonicPatternsBase.Models.HarmonicPattern

@{
    string imageContent = "~/images/patterns/uklad1.png";
    string userImageContent = "~/images/DefaultUserPhoto.png";

    var r = new Random();
    var i = r.Next(0, 5);
    if (i == 0)
    {
        imageContent = "~/images/patterns/uklad1.png";
    }
    else if (i == 1)
    {
        imageContent = "~/images/patterns/uklad2.png";
    }
    else if (i == 2)
    {
        imageContent = "~/images/patterns/uklad3.png";
    }
    else if (i == 3)
    {
        imageContent = "~/images/patterns/uklad4.png";
    }
}
<div class="item" style="margin: 0 0 1em">

    @if (Model.Image.Length > 5)
    {
        var base64 = Convert.ToBase64String(Model.Image);
        imageContent = String.Format("data:image/gif;base64,{0}", base64);
    }

    <div class="row">
        <div class="col-md-2">
            <a asp-action="Details" asp-route-id="@Model.Id">
                <div style="text-align:center">
                    <img src='@imageContent' class="img-rounded" style="max-width:160px" asp-append-version="true" />
                </div>
            </a>
        </div>
        <div class="col-md-10">
            <div class="row">
                <a asp-action="Edit" class="btn button-purple" style="margin-left:25px;">@Model.Instrument.Name</a>
                <a asp-action="Edit" class="btn button-green">@Model.Interval.Name</a>
                <a asp-controller="Patterns" asp-action="Details" asp-route-id="@Model.PatternType.Id" class="btn button-blue">@Model.PatternType.Name</a>
                <a asp-action="Edit" class="btn button-pink">@Model.PatternDirect.Name</a>
            </div>
            <div class="row" style="margin-top:20px;">
                <div class="col-md-4">

                    @if (Model.User == null)
                    {
                        <img src='~/images/DefaultUserPhoto.png' class="img-circle" style="height:70px; width:70px; display:inline-block;" />
                    }
                    else
                    {
                        var base64 = Convert.ToBase64String(Model.User.Avatar);
                        userImageContent = String.Format("data:image/gif;base64,{0}", base64);
                        <img src='@userImageContent' class="img-circle" style="height:70px; width:70px; display:inline-block;" />
                    }

                    @if (Model.User == null)
                    {
                        <a asp-action="Edit" class="text text-blue" style="margin-left:5px; display:inline-block; font-size:12px;">NIEZNANY UZYTKOWNIK</a>
                    }
                    else
                    {
                        <a asp-action="Edit" class="text text-blue" style="margin-left:5px; display:inline-block; font-size:12px;">@Model.User.Nick.ToUpper()</a>
                    }
                </div>
                <div class="col-md-5">
                    <div class="text row" style="margin-top:10px; font-size:12px;">
                        <div class="col-md-3">
                            <p>
                                NA RYNKU:
                            </p>
                        </div>
                        <div class="col-md-8">
                            <p>
                                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                                @Html.DisplayFor(modelItem => Model.Date)
                                <span style="margin-left:7px;" class="glyphicon glyphicon-time" aria-hidden="true"></span>
                                @Model.Date.TimeOfDay
                            </p>
                        </div>
                    </div>
                    <div class="text row" style="margin-top:10px; font-size:12px;">
                        <div class="col-md-3">
                            <p>
                                DODANO:
                            </p>
                        </div>
                        <div class="col-md-7">
                            <p>
                                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                                @Html.DisplayFor(modelItem => Model.AddDate)

                            </p>
                        </div>
                    </div>
                    <div class="text row" style="margin-top:10px; font-size:12px;">
                        <a asp-action="Details" asp-route-id="@Model.Id" class="btn button-blueframe" style="background-color:#ffffff" >Szczegoly</a>
                    </div>
                </div>
                <div class="col-md-3">

                    <div class="col-md-6">
                        <div class="text row" style="margin-top:10px; font-size:12px;">
                            <div class="col-md-4">
                                <p>
                                    R5:
                                </p>
                            </div>
                            <div class="col-md-7">
                                <p>
                                    <a asp-controller="Info" asp-action="Reactions" style="color:#920063"><strong>@Model.ReactionAfter5Candles.Name</strong></a>    
                                </p>
                            </div>
                        </div>
                        <div class="text row" style="margin-top:10px; font-size:12px;">
                            <div class="col-md-4">
                                <p>
                                    R10:
                                </p>
                            </div>
                            <div class="col-md-7">
                                <p>
                                    <a asp-controller="Info" asp-action="Reactions" style="color:#920063"><strong>@Model.ReactionAfter10Candles.Name</strong></a>  
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="text row" style="margin-top:10px; font-size:12px;">
                            <div class="col-md-4">
                                <p>
                                    R20:
                                </p>
                            </div>
                            <div class="col-md-7">
                                <p>
                                    <a asp-controller="Info" asp-action="Reactions" style="color:#920063"><strong>@Model.ReactionAfter20Candles.Name</strong></a>  
                                </p>
                            </div>
                        </div>
                    </div>

                    
                </div>
            </div>
        </div>
    </div>

</div>

src/FiboBase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Harmonic Base</title>
    <link rel="shortcut icon" type="image/ico" href="http://www.phdev.pl/favicon.ico">

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
@*
    <a asp-area="" asp-controller="HarmonicPatterns" asp-action="Index" class="navbar-brand">
        <img src="~/images/patterns/uklad1.png" class="img-circle" style="width:30px; height:30px" />
    </a>
*@

    <a asp-area="" asp-controller="HarmonicPatterns" asp-action="Index" class="navbar-brand">Baza układów</a> 

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Statistics" asp-action="Index">Statystyki i analiza</a></li>
                    <li><a asp-area="" asp-controller="Patterns" asp-action="Index">Układy harmoniczne</a></li>
                    <li><a asp-area="" asp-controller="Info" asp-action="Patterns">Info</a></li>
                </ul>
                @*<a asp-area="" asp-controller="HarmonicPatterns" asp-action="Create" class="btn button-navframe" style="margin-top:10px;">Dodaj</a>*@
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    
     @RenderBody()



    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>